import type { Project } from "$lib/types";

export const labels = [
  "generative",
  "sculpture",
  //   "code",
  "lighting",
  "AI",
  "web",
  "tool",
  "research-art",

  // 'video'
];

export const projects: Project[] = [
  {
    name: "About",
    labels: [],
    img: "imgs/lamp_me_square.jpg",
    year: undefined,
    hide: false,
    description: "Hi, I'm Joel",
    path: "/about",
  },
  {
    name: "Latent Lineages",
    path: "latent-lineages",
    labels: ["generative", "AI", "research-art"],
    img: "imgs/latent-lineages/2ed186e54b66618a7167_icon.jpg",
    // img: "imgs/latent-lineages/40cef9bdd29d3384fa5f630945ba_icon.png",
    // img: "imgs/latent-lineages/e5d34030a7dd0ae2a2b0956edf7d_4096_neato_layout.jpeg",
    year: 2025,
    description:
      "Visualizing the genealogical networks of individual images from Artbreeder.",
  },
  {
    name: "Lluminate",
    path: "lluminate",
    labels: ["generative", "AI", "research-art"],
    img: "lluminate/preview-2.jpg",
    year: 2025,
    description: "An evolutionary algorithm for creative exploration.",
  },
  {
    name: "Webpage of Forgotten Dreams",
    year: 2024,
    labels: ["web", "tool"],

    img: "imgs/thumbnails/hands-preview.jpg",
    path: "forgotten-dreams",
    description: "Create cave paintings.",
  },
  {
    name: "ClickSynth",
    year: 2024,
    labels: ["web", "tool", "AI"],

    img: "imgs/thumbnails/clicksynth.jpg",
    // path: 'puppets',
    externalPath: "https://clicksynth.com",
    description: "A kind of 'shader-breeder' using language models.",
  },
  {
    name: "Puppets App",
    year: 2024,
    labels: ["web", "tool"],

    img: "imgs/puppets/preview.jpg",
    // path: 'puppets',
    externalPath: "https://puppets.app/",
    description:
      "Collaborative online puppet studio and theater. An experiment in creative tools based on principles of craft, play and collaboration by StudioMorphogen.",
  },
  {
    name: "Masterpiece, best quality, highres",
    path: "masterpiece",
    year: 2024,
    labels: ["AI"],

    img: "imgs/masterpiece/preview.jpg",
    description:
      "Exploration of how AI upscalers absurdly transform abstract shapes into containers of feminine features whenever prompted for 'masterpiece' quality.",
  },
  {
    name: "LatentScape",
    year: 2024,
    externalPath: "https://latentscape.com",
    labels: ["web", "AI"],
    img: "imgs/thumbnails/latentscape.jpg",
    description:
      "A virtual world for exploring and creating images with others.",
  },
  {
    name: "Ceramic Lamp 2",
    year: 2023,
    labels: ["lighting", "sculpture"],
    img: "imgs/thumbnails/ceramic-lamp-2.jpeg",
    description: "Hand built ceramic lamp.",
  },
  {
    name: "New Words",
    year: 2023,
    path: "new-words",
    labels: ["generative", "code", "AI", "research-art"],
    img: "imgs/new-words/cover4.webp",
    description: "Expanding the english language.",
  },
  {
    name: "Ceramic Lamp 1",
    year: 2022,
    path: "ceramic-lamp",
    labels: ["lighting", "sculpture"],
    img: "imgs/thumbnails/ceramic-lamp.jpg",
    description: "Learning the process of slip casting.",
  },
  {
    name: "ProsePainter",
    year: 2021,
    labels: ["AI", "tool"],
    img: "imgs/thumbnails/prosepainter.jpg",
    description:
      "An interactive tool to “paint with words.” It incorporates guidable text-to-image generation into a traditional digital painting interface. ",
  },
  {
    name: "GAN Portraits",
    year: 2021,
    labels: ["generative", "code", "AI"],
    img: "imgs/thumbnails/gan-portrait.jpg",
    description: "Generative face collages using machine learning.",
  },
  {
    name: "Emotional Bounds",
    year: 2020,
    labels: ["web", "AI"],
    img: "imgs/emotional-bounds/preview.png",
    externalPath:
      "https://joels-share.s3.amazonaws.com/emotional-bounds/prototype/index.html",
    description:
      "Capturing the expressions that most confuse machine learning classifiers. Mapping beyond the bounds of classification allows users to create an intimate understanding of their own spaces of expression.",
  },
  {
    name: "Derivative Works",
    year: 2020,
    labels: ["generative", "web", "code", "AI", "research-art"],
    img: "imgs/derivative-works-2.jpg",
    externalPath: "https://derivative.works",
    description: "Generative face collages using machine learning.",
  },
  {
    name: "Generative Portraits",
    year: 2020,
    labels: ["generative", "web", "code"],
    img: "imgs/evo-portraits/icon2.png",
    // img: 'imgs/thumbnails/evo-portraits.jpg',
    description: "Generative faces using genetic algorithms.",
  },
  {
    name: "Artbreeder Interviews",
    labels: ["generative", "web", "video"],
    img: "imgs/ab_interviews_icon.png",
    year: 2020,
    hide: false,
    description:
      "Generative video of interviews with members of the Artbreeder community about how they are using machine learning and Artbreeder in their creative practices.",
  },
  {
    name: "Forms Of Life",
    labels: ["generative", "code", "research-art"],
    img: "imgs/forms-of-life/icon.png",
    year: 2020,
    hide: false,
    description: "Experimental generative architecture for artificial life.",
  },
  {
    name: "Antimander",
    labels: ["generative", "code", "web", "research-art"],
    img: "imgs/download.png",
    year: 2020,
    hide: false,
    externalPath: "http://www.antimander.org",
    description:
      "A research paper, interactive blog and open-source library for fighting gerrymandering via generative methods.",
  },
  {
    name: "Reaction Diffusion 3D",
    year: 2020,
    img: "imgs/webgl-rd.png",
    labels: ["code", "web"],
    externalPath: "https://joels-share.s3.amazonaws.com/rd_shapes/index.html",
    description: "View a 3D reaction diffusion simulation in the browser.",
  },
  {
    name: "Table Lamp 4",
    labels: ["lighting"],
    img: "imgs/table-lamp-4/icon.jpg",
    year: 2019,
    description: "Table lamp.",
  },
  {
    name: "Neural Tablets",
    labels: ["generative", "sculpture", "AI"],
    img: "imgs/tablets/icon.png",
    path: "/tablets",
    year: 2019,
    hide: false,
    description:
      "An extension of my Dimensions of Dialogue set in clay tablets.",
  },
  {
    name: "Coral Video",
    labels: ["generative", "code", "video"],
    img: "imgs/coral_video/icon.jpg",
    year: 2019,
    hide: false,
    description: "A music video of my Corals project.",
  },
  {
    name: "Morphogen Site",
    path: "/morphogen",
    labels: ["generative", "code", "web"],
    img: "imgs/morphogen.jpg",
    year: 2019,
    hide: false,
    description: "Website made in reaction diffusion shaders.",
  },
  {
    name: "Dimensions of Dialogue",
    labels: ["generative", "code", "AI", "research-art"],
    img: "imgs/dod/binary_model_10.png",
    img2: "imgs/dod/grid-3x3.jpg",
    year: 2018,
    hide: false,
    description:
      "Experiments inspired by early proto-writing systems such as cuneiform and hieroglyphs. Here, new writing systems are created by challenging two neural networks to communicate information via images",
  },
  {
    name: "Ganbreeder",
    labels: ["generative", "web", "AI", "tool"],
    img: "imgs/ganbreeder2.jpg",
    description: "A website to breed images collaboratively.",
    year: 2018,
  },
  {
    name: "Desk Lamp 3",
    labels: ["lighting"],
    img: "imgs/desk-lamp-3/icon2.jpg",
    year: 2018,
  },
  {
    name: "Corals",
    labels: ["generative", "code", "research-art"],
    img: "imgs/corals/icon.jpg",
    year: 2018,
    description: "Generative forms art-research",
  },
  {
    name: "Ecosystem Modelling",
    labels: ["generative", "code", "video", "research-art"],
    img: "imgs/ecosystem-modelling/icon.jpg",
    description: "Modelling ecosystem simulations",
    year: 2017,
  },
  {
    name: "Figuration",
    labels: ["video"],
    img: "imgs/figuration.jpg",
    description:
      "A si-fi short film made during the Imagine Science film festival.",
    year: 2017,
  },
  {
    name: "Plant Lamp",
    labels: ["lighting"],
    img: "imgs/plant-lamp/icon.jpg",
    year: 2017,
    description: "A growth lamp for my succulents.",
  },
  {
    name: "Desk Lamp 2",
    labels: ["lighting"],
    img: "imgs/desk-lamp-2/DSCF4329.jpg",
    year: 2017,
  },
  {
    name: "Evolving Floorplans",
    labels: ["generative", "code", "research-art"],
    img: "imgs/evo_plans/icon.png",
    path: "/evo_floorplans",
    year: 2017,
    description: "Floorplans optimized with a custom genetic algorithm.",
  },
  {
    name: "Simon Lamps",
    labels: ["lighting", "web", "code"],
    img: "imgs/simon-lamps/icon.jpg",
    year: 2016,
    description: "A website for my lamps.",
  },
  {
    name: "Desk Lamp 1",
    labels: ["lighting"],
    img: "imgs/desk_lamp_1b/DSCF4294.jpg",
    year: 2016,
  },
  {
    name: "Wall Lamp",
    labels: ["lighting"],
    img: "imgs/wall-lamp/wall-lamp-icon.jpg",
    year: 2016,
  },
  {
    name: "Sculpture Drop",
    labels: ["generative", "sculpture"],
    img: "imgs/sculpture-drop/icon.png",
    year: 2016,
    description:
      "Simulating the destruction of my sculptures by being dropped in a fracture simulation.",
  },
  {
    name: "Table lamp 3",
    labels: ["lighting"],
    img: "imgs/table-lamp-3/icon.jpg",
    year: 2015,
  },

  {
    name: "Tanya",
    labels: ["sculpture"],
    img: "imgs/tanya/icon.png",
    year: 2015,
    description: "Clay figure sculpture cast in plaster.",
  },
  {
    name: "Table lamp 2",
    labels: ["lighting"],
    img: "imgs/table-lamp-2/icon.jpg",
    year: 2015,
  },
  {
    name: "Facebook Graffiti",
    labels: ["code", "web"],
    img: "imgs/fb-graffiti.jpg",
    year: 2015,
    description: "A collaborative anarchist art making chrome extension.",
  },

  {
    name: "Scrap",
    labels: ["web", "code"],
    img: "imgs/scrap.png",
    year: 2015,
  },
  {
    name: "Slice",
    labels: ["generative", "sculpture", "code"],
    img: "imgs/slice.jpg",
    year: 2014,
    description: "Parametric geometric sculpture.",
  },
  {
    name: "Graph Contraction",
    labels: ["generative", "code", "sculpture"],
    img: "imgs/graph-contraction/graph-contraction.png",
    year: 2014,
    description: "Graph contraction algorithms applied to 3D meshes.",
  },
  {
    name: "Maria",
    labels: ["sculpture"],
    img: "imgs/maria/icon2.png",
    year: 2013,
    description: "A life size figure sculpture cast in plaster.",
  },
  {
    name: "Image To Paint",
    labels: ["generative", "code"],
    img: "imgs/image-to-paint/icon.jpg",
    year: 2012,
    description: "Software to convert an image to strokes.",
  },
  {
    name: "Head in Hands",
    labels: ["sculpture"],
    img: "imgs/head-in-hands/icon.JPG",
    year: 2012,
  },
  {
    name: "Cornered Hands",
    labels: ["sculpture"],
    img: "imgs/cornered-hands/icon.jpg",
    year: 2012,
  },
  {
    name: "Small-talk Robot",
    labels: ["code"],
    img: "imgs/smalltalk/smalltalk_square.jpg",
    year: 2012,
    description: "A robot that will make small talk with the viewer.",
  },
  {
    name: "Mosaic Table",
    labels: [],
    img: "imgs/mosaic-table/table_square.jpg",
    year: 2007,
  },
];
