runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1h"

handlers:

- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

- url: /*
  static_files: www/index.html
  upload: www/index.html


