<div class="text_body">
  <h2>Limitations and Future work</h2>
  <p>
    <strong>Optimized strategies:</strong>
    The creative strategies were effective but arbitrarily created and there was
    no thorough evaluation of their ideal structure or content. This sets the stage
    for potentially co-evolving strategies alongside artifacts that adapt to specific
    domains. These evolved "chain of creative thought templates" could even be reusable
    in direct prompting.
  </p>
  <p>
    <strong>Quality and Constraints:</strong>
    This algorithm can fail to produce valid outputs when the constraints are not
    innately satisfied by the LLM. Currently, it lacks mechanisms to repair infeasible
    solutions or enforce minimal quality criteria. Potential improvements include
    applying selection criteria to the reproducing population or leveraging the multimodal
    capabilities of models to "see" outputs via image inputs. At the time of writing,
    image capabilities were not yet available in the o3-api, though this will likely
    change soon. In the future, if costs decrease, the entire population could be
    presented as images, allowing selection pressure to be applied based on phenotypes
    (visual outputs) rather than textual summaries of genomes.
  </p>
  <p>
    <strong>Concept / Implementation barrier:</strong>
    Large outputs become costly to generate for every generation, an alternative
    approach is to only generate a shorter description of the central idea for the
    object and then do a run with a more powerful model for the final generations.
    Analogies to how most projects get evaluated at the concept phase. The main challenge
    is that many concepts generated by the LLM are impractical, diverge greatly when
    generated or are hard to articulate (such as shaders which are hard to describe
    in text). Potential future work could look to bridge this gap.
  </p>
  <p>
    <strong>Creative Reasoning Analysis:</strong> It would be illuminating to view
    and analyze the model's reasoning on the different strategies to better understand
    how it is interpreting the creative strategies. The API from OpenAI does not
    enable viewing the reasoning output, but open source reasoning models are rapidly
    improving.
  </p>
</div>
